server:
  port: 8080
spring:
  application:
    name: gateway-service
zuul:
  routes:
    product-service:
      path: /products/**
      serviceId: product-service
    order-service:
      path: /orders/**
      serviceId: order-service
    user-service:
      path: /users/**
      serviceId: user-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
