version: '3.8'

services:
  config-service:
    build: ./config-service
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - config-service

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - config-service
      - discovery-service

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - config-service
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - config-service
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  user-service:
    build: ./user-service
    ports:
      - "8083:8083"
    depends_on:
      - config-service
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
